# yet another python formatter
- repo: git://github.com/pre-commit/mirrors-yapf
  rev: v0.27.0
  hooks:
  - id: yapf

# prospector: collection of linters
- repo: git://github.com/guykisel/prospector-mirror
  rev: 7ff847e779347033ebbd9e3b88279e7f3a998b45
  hooks:
  - id: prospector
    # need to install prospector in the same python environment
    # for checking import errors
    language: system
    types: [file, python]

# modernizer: make sure our code-base is Python 3 ready
- repo: https://github.com/python-modernize/python-modernize.git
  rev: a234ce4e185cf77a55632888f1811d83b4ad9ef2
  hooks:
  - id: python-modernize
    exclude: ^docs/
    args:
      - --write
      - --nobackups
