# yet another python formatter
- repo: git://github.com/pre-commit/mirrors-yapf
  rev: v0.27.0
  hooks:
  - id: yapf

# prospector: collection of linters
- repo: git://github.com/guykisel/prospector-mirror
  rev: 7ff847e779347033ebbd9e3b88279e7f3a998b45
  hooks:
  - id: prospector
    # need to install prospector in the same python environment
    # for checking import errors
    language: system
    types: [file, python]
